name: GM4UHC
main: co.gm4.uhc.GM4UHC
authors: [MrSugarCaney]
version: '1.2pre'
description: >
             Gamemode 4 UHC plugin
commands:
  lack:
    description: Shows all the teams that lack players.
    permission: uhc.mod
    aliases: [tlack, tnotenough, notenough]
  switch:
    description: Teleport between lobby and world.
    permission: uhc.mod
  setlobby:
    description: Sets the location of the lobby spawn.
    permission: uhc.mod
  warn:
    description: Warns a player.
    permission: uhc.mod
  die:
    description: Removes a player from the game.
    permission: uhc.mod
  close:
    description: Closes the server; all players will be spectators.
    permission: uhc.mod
  start:
    description: Starts the countdown and the match itself.
    permission: uhc.mod
  autoteam:
    description: Puts a given player in the first empty spot in a team.
    permission: uhc.mod
    aliases: [auto, tauto]
  parseteams:
    description: Reads the teams from the configuration file.
    permission: uhc.mod
    aliases: [parse, tparse]
  teamless:
    description: Shows who aren't in a team.
    aliases: [tless, noteam]
  teamlist:
    description: Shows a list with all teams.
    aliases: [tlist, tl]
  remove:
    description: Removes a player from their team.
    permission: uhc.mod
    aliases: [rem, tr]
  colours:
    description: Shows a list of all available colours and accents.
    permission: uhc.mod
    aliases: [colors, accents]
  teamcolour:
    description: Changes the colour of a player's team. See also /colours for a list of colours and accents.
    permission: uhc.mod
    aliases: [tc, teamc, teamcolor, ta, teama, teamaccent]
  team:
    description: Puts all the given players in a team.
    permission: uhc.mod
    aliases: [t]
  silence:
    description: Only show mod messages.
  mute:
    description: (Un)mutes a player.
    permission: uhc.mod
    aliases: [unmute]
  unmuteall:
    description: Unmutes all players.
    permission: uhc.mod
  mod:
    description: Send a message to all moderators.
    permission: uhc.mod
    aliases: [modmsg, modmail, mail]
  shout:
    description: Broadcast a message to all players.
    permission: uhc.mod
    aliases: [broadcast]
  uhc:
    description: Gamemode 4 UHC Help
  gm4:
    description: Gamemode 4 Info