name: GM4UHC
main: co.gm4.uhc.GM4UHC
authors: [MrSugarCaney]
version: '0.18'
description: >
             Gamemode 4 UHC plugin
commands:
  silence:
    description: Only show mod messages.
  mute:
    description: (Un)mutes a player.
    permission: uhc.mod
    aliases: [unmute]
  unmuteall:
    description: Unmutes all players.
    permission: uhc.mod
  mod:
    description: Send a message to all moderators.
    permission: uhc.mod
    aliases: [modmsg, modmail, mail]
  shout:
    description: Broadcast a message to all players.
    permission: uhc.mod
    aliases: [broadcast]
  uhc:
    description: Gamemode 4 UHC Help
    permission: uhc.mod
  gm4:
    description: Gamemode 4 Info